const PLAYLIST_ID="PLMwCOELsaIao";let player=null,ready=false,muted=false,timer;
const $=id=>document.getElementById(id),fmt=n=>{n=Math.max(0,Math.floor(Number(n)||0));return String(Math.floor(n/60)).padStart(2,"0")+":"+String(n%60).padStart(2,"0")};
function track(){if(!ready)return;const d=player.getVideoData?player.getVideoData():{},t=d.title||"4.20 INTERNET RADIO";$("title").textContent=t;if(d.video_id)$("art").style.backgroundImage=`url("https://i.ytimg.com/vi/${d.video_id}/hqdefault.jpg")`;$("art").style.backgroundSize="cover";$("art").style.backgroundPosition="center";document.title=t+" — SMOKE FM"}
function progress(){if(!ready)return;const d=player.getDuration(),c=player.getCurrentTime(),p=d?c/d*100:0;$("bar").style.width=p+"%";$("dot").style.left=p+"%";$("cur").textContent=fmt(c);$("dur").textContent=fmt(d)}
function update(){clearInterval(timer);timer=setInterval(progress,500)}
function toggle(){if(!ready)return;player.getPlayerState()===YT.PlayerState.PLAYING?player.pauseVideo():player.playVideo()}
window.onYouTubeIframeAPIReady=()=>{player=new YT.Player("player",{width:"280",height:"158",playerVars:{autoplay:1,controls:0,playsinline:1,rel:0,listType:"playlist",list:PLAYLIST_ID,origin:location.origin},events:{onReady:()=>{ready=true;player.setVolume(72);setTimeout(track,700);update()},onStateChange:e=>{if(e.data===YT.PlayerState.PLAYING){$("play").textContent="Ⅱ";track();update()}else if(e.data===YT.PlayerState.PAUSED){$("play").textContent="▶";progress()}else if(e.data===YT.PlayerState.ENDED)player.nextVideo()},onError:e=>console.log("YT",e.data)}})};
const y=document.createElement("script");y.src="https://www.youtube.com/iframe_api";document.head.appendChild(y);
$("play").onclick=toggle;$("next").onclick=()=>ready&&player.nextVideo();$("prev").onclick=()=>ready&&player.previousVideo();$("shuffle").onclick=()=>{if(ready){player.setShuffle(true);player.playVideoAt(Math.floor(Math.random()*(player.getPlaylist()||[]).length))}};$("mute").onclick=()=>{if(!ready)return;muted=!muted;muted?player.mute():player.unMute();$("mute").textContent=muted?"×":"⌁"};$("progress").onclick=e=>{if(!ready)return};
document.querySelector(".progress>div:first-child").onclick=e=>{if(!ready)return;const r=e.currentTarget.getBoundingClientRect();player.seekTo(player.getDuration()*Math.max(0,Math.min(1,(e.clientX-r.left)/r.width)),true)};
document.querySelectorAll(".station-strip button").forEach(b=>b.onclick=()=>{document.querySelectorAll(".station-strip button").forEach(x=>x.classList.remove("active"));b.classList.add("active")});
function clock(){$("clock").textContent=new Date().toLocaleTimeString([],{hour:"2-digit",minute:"2-digit"})}setInterval(clock,1000);clock();
setInterval(()=>{const n=1580+Math.floor(Math.random()*150);$("listeners").textContent=n.toLocaleString();$("listenersTop").textContent=n.toLocaleString()},5000);
